server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
      #mysql5.x的没有cj
    driver-class-name: org.gjt.mm.mysql.Driver
    #记得先创建数据库
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.zko0.springcloud.entities  #所有Entity别名类所在包


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示Ip地址
    #Eureka客户端向Server发送心跳的间隔时间，单位时秒（默认是30s）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在接收到最后一次心跳后等待时间的上限，单位是秒（默认90s），超时删除服务
    lease-expiration-duration-in-seconds: 2
