server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos
    sentinel:
      transport:
        dashboard: localhost:8858    #sentinel
        client-ip: 192.168.31.30
        port: 8719

#激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true
