server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka
#需要加上，否则会报错
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
feign:
  hystrix:
    enabled: true
  #下面两行不要，但是需要注意
  #httpclient:
  #  connection-timeout: 5000


